Update MediaVox-Pubilsh.yml

diff --git a/.github/workflows/MediaVox-Pubilsh.yml b/.github/workflows/MediaVox-Pubilsh.yml
--- a/.github/workflows/MediaVox-Pubilsh.yml
+++ b/.github/workflows/MediaVox-Pubilsh.yml
@@ -27,12 +27,27 @@ jobs:
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
 
+      - name: Find libs.versions.toml
+        id: find_libs_versions
+        run: |
+          find . -type f -name "libs.versions.toml" -print -quit > libs_versions_path.txt || echo "File not found"
+          if [ -s libs_versions_path.txt ]; then
+            echo "::set-output name=libs_versions_path::$(cat libs_versions_path.txt)"
+          else
+            echo "::set-output name=libs_versions_path::"
+          fi
+
       - name: Retrieve Previous Version Code
         id: retrieve_previous_version
         run: |
-          previous_version=$(awk -F "=" '/^app-version-versionCode/ {print $2}' MediaVox/gradle/libs.versions.toml)
-          echo "::set-output name=previous_version::$previous_version"
-
+          if [ -n "${{ steps.find_libs_versions.outputs.libs_versions_path }}" ]; then
+            previous_version=$(awk -F "=" '/^app-version-versionCode/ {print $2}' "${{ steps.find_libs_versions.outputs.libs_versions_path }}")
+            echo "::set-output name=previous_version::$previous_version"
+          else
+            echo "No libs.versions.toml found"
+            echo "::set-output name=previous_version::0"  # Default to 0 if file not found
+          fi
+          
       - name: Get Current Version Code
         id: get_current_version
         run: echo "::set-output name=current_version::$(./gradlew printVersionCode --quiet)"
